apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pod
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pod
    spec:
      containers:
        - name: agent
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7777
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 3000
      serviceAccountName: {{ .Release.Name }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default .Release.Name .Values.serviceAccountName }}
