apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7777
      targetPort: http
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-pod
    