apiVersion: v1
kind: Service
metadata:
  name: app2service
spec:
  type: NodePort
  selector:
    app: app2
  ports:
    - port: 6666 # service's port. A pod will communicate to app1 pod from 6666 to 8888. 6666 is internal cluster port
      targetPort: 8888
      nodePort: 30003 # a node will communicate to app1 pod from 30003 to 8888 from outside the cluster