name: Docker build and publish
on:
  pull_request:
    paths:
      - .github/workflows/*
      - cmd/**
      - pkg/**
      - go.mod
      - ip-returner.go

  push:
    branches:
      - main
    paths:
      - .github/workflows/*
      - cmd/**
      - pkg/**
      - go.mod
      - ip-returner.go

env:
  REGISTRY: artifactory.novus.legogroup.io
  REPO: novus-api
  IMAGE: novus-echo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx 🐋 #action will create and boot a builder using by default the docker-container driver.
        uses: docker/setup-buildx-action@v2

      - name: Login to JFrog 🐸 #action will take care to log in against a Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          # We will need a JFROG_USER and TOKEN secret injected, we will cover that in a minute
          username: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_TOKEN }}

      - name: Get package version
        id: package-version
        run: |
          echo "version=$(git show -s --format=%cd --date=format:%Y%m%d HEAD)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push 🐳
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          provenance: false
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE }}:${{ steps.package-version.outputs.version }}
          build-args: |
            VERSION=${{ steps.package-version.outputs.version }}
